### ISSUE TITLE
The output generated for Example 1 is not correct

### ISSUE THREAD

**Issue by mengrj** [ModelInference/texada#84]
When running Example 1 with the command `./texada -m -f 'G(x -> X(F(y)))' --log-file basic_log.txt` and the same log format as the  `basic_log.txt` file, texada produces the following output. However, only `G(c -> XFd)` should be the correct LTL property, and others should be the incorrect results. Is there any way to filter out the incorrect results? I am not sure whether I could use other command options to filter out incorrect properties. 
`G(a -> XFc)`
`G(a -> XFd)`
`G(b -> XFc)`
`G(b -> XFd)`
`G(c -> XFd)`

I ran it on ubuntu 20.04 and ubuntu 14.04, and the whole installation process didn't report any errors. But on both systems, it produces the same incorrect results.

**Comment by bestchai** [comment]
Try adding the --no-vacuous-findings option

**Comment by mengrj** [comment]
Thanks. It works now with: `./texada -l -f 'G(x -> X(F(y)))' --log-file basic_log.txt --no-vacuous-findings`
